# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site.
# These values are expected to rarely change. If you are editing this file
# very often, consider using Jekyll's data files feature.

## Site settings
## https://jekyllrb.com/docs/configuration/

# Plugins
plugins:
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from

# Theme
# Not currently used, but not specifying results in github-pages
# defaulting to compile Primer SASS, which causes problems.
# https://github.com/jekyll/jekyll/issues/7426
theme: minima

# Conversion
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

# Search
algolia:
  application_id: HOJ487LP0L
  # Which index the Travis job will create/update
  # with the content of the current Jekyll site.
  # The auth key for this is injected as secure env variable.
  index_name: qunitjs-api
  # Auth key for client-side search queries.
  search_only_api_key: aed00982db05bd21dd05310be057bda8

# Serving
baseurl: ""

# Input files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CONTRIBUTING.md
  - CNAME

# Output
permalink: title/

## Site variables
## accessible via `{{ site.* }}` in layouts.
